version: '3.8'


services:
  web:
    build: .
    command: go run main.go -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/armuseum
  s3service:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /minio_data
    hostname: minio1
#    network_mode: host
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /home/dskom/home_projects/minio_data:/minio_data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - /home/dskom/home_projects/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: armuseum_db
